apiVersion: apps/v1
kind: Deployment
metadata:
  name: charges-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charges
  template:
    metadata:
      labels:
        app: charges
    spec:
      containers:
        - name: charges
          image: felixphil/charges
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: artisans
            - name: MONGO_URI
              value: "mongodb://charges-mongo-srv:27017/charges"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: FLUTTERWAVE_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: flutterwave-secret
                  key: FLUTTERWAVE_PUBLIC
            - name: FLUTTERWAVE_SECRET
              valueFrom:
                secretKeyRef:
                  name: flutterwave-secret
                  key: FLUTTERWAVE_SECRET
            - name: REDIS_HOST
              value: charges-redis-srv
---
apiVersion: v1
kind: Service
metadata:
  name: charges-srv
spec:
  selector:
    app: charges
  ports:
    - name: charges
      protocol: TCP
      port: 3000
      targetPort: 3000
