apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: felixphil/subscription
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: artisans
            - name: MONGO_URI
              value: 'mongodb://subscription-mongo-srv:27017/subscription'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-srv
spec:
  selector:
    app: subscription
  ports:
    - name: subscription
      protocol: TCP
      port: 3000
      targetPort: 3000
