apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  template:
    metadata:
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: felixphil/transactions
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: artisans
            - name: MONGO_URI
              value: "mongodb://transactions-mongo-srv:27017/transactions"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: FLUTTERWAVE_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: flutterwave-secret
                  key: FLUTTERWAVE_PUBLIC
            - name: FLUTTERWAVE_SECRET
              valueFrom:
                secretKeyRef:
                  name: flutterwave-secret
                  key: FLUTTERWAVE_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: transactions-srv
spec:
  selector:
    app: transactions
  ports:
    - name: transactions
      protocol: TCP
      port: 3000
      targetPort: 3000
